//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryGetter.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAisleProduct
    {
        public System.Guid Id { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid AisleId { get; set; }
    
        public virtual tblAisle tblAisle { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
