//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryGetter.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLayout()
        {
            this.tblAisles = new HashSet<tblAisle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StoreId { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAisle> tblAisles { get; set; }
        public virtual tblStore tblStore { get; set; }
    }
}
